### PR TITLE
Fix type piracy

### PR DESCRIPTION
**Pull request by sumiya11**
Running CI..

The lower bound on the AA.jl version is changed since AbstractAlgebra.vars for fractions is released in v0.34.5:
https://github.com/Nemocas/AbstractAlgebra.jl/releases/tag/v0.34.5

Merge me before #253

### CODE REVIEW

**Comment by sumiya11** [comment]
Now Groebner.jl (0.6.3) handles both Nemo.GF/Nemo.Native.GF, and ParamPunPam.jl (0.3.1) internally uses Nemo.Native.GF.

Therefore, here, I decided to set sharp lower bounds for Groebner.jl and ParamPunPam.jl.

**Comment by sumiya11** [comment]
Now that MTK seems to have dropped support for Julia 1.6, should we move to Julia 1.9 as well? @pogudingleb

**Comment by pogudingleb** [comment]
> Now that MTK seems to have dropped support for Julia 1.6, should we move to Julia 1.9 as well? @pogudingleb

Are you asking because you foresee any problems with keeping 1.6?

Is there any discussion about dropping the support of 1.6 in MTK? The LTS seem to be still 1.6 according to the [Julia webpage](https://julialang.org/downloads/)...

**Comment by sumiya11** [comment]
> Are you asking because you foresee any problems with keeping 1.6?

It could be harder to maintain `mtk_to_si` and friends in SI.jl, since we would't get updates from MTK and Symbolics anymore.

> Is there any discussion about dropping the support of 1.6 in MTK? 

Not that I know of, unfortunately

**Comment by pogudingleb** [comment]
Superseded by #274

**Pull request closed without merging**
