### PR TITLE
Fix a bug in PreprocessODE

### PR DESCRIPTION
**Pull request by iliailmer**
Was preventing from running examples like below:
```julia
using StructuralIdentifiability, ModelingToolkit
@parameters k1 k2 eB
@variables t xA(t) xB(t) xC(t) eA(t) eC(t) y1(t) y2(t) y3(t) y4(t)
D = Differential(t)
eqs = [
    D(xA) ~ -k1 * xA,
    D(xB) ~ k1 * xA - k2 * xB,
    D(xC) ~ k2 * xB,
    D(eA) ~ 0,
    D(eC) ~ 0,
]
measured_quantities = [
    y1 ~ xC,
    y2 ~ eA * xA + eB * xB + eC * xC,
    y3 ~ eA,
    y4 ~ eC
]
@named ode = ODESystem(eqs, t)
result = assess_identifiability(ode, measured_quantities=measured_quantities)
```

### CODE REVIEW

**Comment by pogudingleb** [comment]
Thanks!
Could you add this as a test-case to the tests?

**Comment by iliailmer** [comment]
> Thanks! Could you add this as a test-case to the tests?

I'm working on tests, but here is an issue I am not certain how to resolve. Consider this example:

```julia
 @parameters a b c 
    @variables t x1(t) x2(t) y(t)
    D = Differential(t)

    eqs = [
        D(x1) ~ -a * x1 + x2 * b / (x1 + b / (c^2 - x2)),
        D(x2) ~ x2 * c^2 + x1
    ]
    de = ODESystem(eqs, t, name=:Test)
    measured_quantities = [y ~ x2]
    correct = Dict(a => :globally, b => :globally, c => :locally)
    to_check = [a, b, c]
```

In [this line](https://github.com/SciML/StructuralIdentifiability.jl/blob/ea6988f87439ccf0ece96686ed477b2927361fc6/src/util.jl#L288) of `eval_at_nemo`, the comparison happens of an `fmpq_mpoly` object (the degree of c) to an `Int`, which results in error. I tried converting 0 on the rhs of the comparison to `fmpq_mpoly` type, but that did not work.

**Comment by pogudingleb** [comment]
Since we allow only integer degrees, we can check here that the degree is integer (e.g., using `numerator`)  and then do `Int(denominator(args[2]))`. Does this make sense?

**Comment by iliailmer** [comment]
I ended up fixing by separately checking if there are ODE like "D(x)~0" before entering `eval_at_nemo`

**Comment by pogudingleb** [comment]
Nice, thank you!

**Pull request merged**
