### PR TITLE
Bump the symbolic libraries and fix deprecations

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by pogudingleb** [comment]
This PR was not passing CI, so I reopened it.
@ChrisRackauckas I would greatly appreciate if PRs which change the code (not only compats) are merged after I look at them.

**Comment by ChrisRackauckas** [comment]
This PR passed all tests? And it was just a depwarn fix?

**Comment by pogudingleb** [comment]
> This PR passed all tests? And it was just a depwarn fix?

Yes, you can say so: it was failing "Downgrade" test because of the devs inconsistency

**Comment by ChrisRackauckas** [comment]
Downgrade CI currently has some false negatives because it needs a different resolver, which will hopefully be something added in the next few months.

**Comment by pogudingleb** [comment]
Glad to hear about these developments in Downgrade. In this case, it actually spotted a mismatch, I have fixed it anyway.

**Pull request merged**
