### PR TITLE
Create a `measured_quantities` input argument for output functions

### PR DESCRIPTION
**Pull request by iliailmer**
This is as per discussion here: https://github.com/SciML/ModelingToolkit.jl/pull/1243

### CODE REVIEW

**Comment by iliailmer** [comment]
unsure about this error:
https://github.com/iliailmer/StructuralIdentifiability.jl/runs/4620269365?check_suite_focus=true#step:5:183

**Comment by pogudingleb** [comment]
> unsure about this error: https://github.com/iliailmer/StructuralIdentifiability.jl/runs/4620269365?check_suite_focus=true#step:5:183

Can you reproduce it locally?

**Comment by pogudingleb** [comment]
This is an interesting terminological collision, great that it is being clarified.
I am a bit concerned about the name `data_series`, it sounds like actual data is provided. Maybe `observables`?

**Comment by iliailmer** [comment]
> > unsure about this error: https://github.com/iliailmer/StructuralIdentifiability.jl/runs/4620269365?check_suite_focus=true#step:5:183
> 
> Can you reproduce it locally?

I checked, there was an `end` missing in main module, should be fixed now.

**Comment by iliailmer** [comment]
> This is an interesting terminological collision, great that it is being clarified.
> I am a bit concerned about the name `data_series`, it sounds like actual data is provided. Maybe `observables`?

Maybe `measured_quantities`? `observables` seems to close to `observed` 😄

**Comment by iliailmer** [comment]
> I checked, there was an `end` missing in main module, should be fixed now.

Strange, the error seems to complain that there is an extra `end` now: https://github.com/SciML/StructuralIdentifiability.jl/runs/4627159607?check_suite_focus=true#step:5:272

but my local version is running fine

**Comment by pogudingleb** [comment]
> Maybe `measured_quantities`? `observables` seems to close to `observed` smile

Good point! `measured_quantities` sounds good to me.

One more thing: right now, it looks like these quantities must be passed as an argument even if they are present in the outputs of the model. How about, if `measured_quantities` are not provided, the outputs of the model are used?

**Comment by iliailmer** [comment]
tests should work now, there was an issue processing parameters that were part of y-functions (`measured_quantities`) but not the ODE.

**Comment by pogudingleb** [comment]
Great! So, with the current interface, one must provide `measured_quantities`, right?

**Comment by iliailmer** [comment]
> Great! So, with the current interface, one must provide `measured_quantities` (that is, not possible to use the outputs of the model), right?

That's right. I think for the case when these are not provided we could use the multiple dispatch?

**Comment by pogudingleb** [comment]
> > Great! So, with the current interface, one must provide `measured_quantities` (that is, not possible to use the outputs of the model), right?
> 
> That's right. I think for the case when these are not provided we could use the multiple dispatch?

Yes, I think this would be the best way to do this.

**Comment by iliailmer** [comment]
I added the multiple dispatch for cases when measured quantities are not provided. the program will look for output equations and will raise an error if those are not passed at all. I think all cases for local and global problems are covered: 

- without measured quantities and without "functions-to-check" (i.e. try finding outputs and use all available parameters), 
- with measured quantities and without "functions-to-check" (use all available parameters)
- without measured quantities and with "functions-to-check" (try finding outputs)
- with both provided (no extra steps to do here)

**Comment by pogudingleb** [comment]
@iliailmer , thank you! 
My concern now if the combinatorics, we have indeed four combinations, adding one additional feature will make the code hardly manageable. How about making `measured_quantities` (and maybe even `funcs_to_check`) keyword parameters? Then there will be a single function with a single initialization step for each of them.

**Comment by pogudingleb** [comment]
@iliailmer , the code looks great! Shouldn't the docs be updated now?

**Comment by iliailmer** [comment]
> @iliailmer , the code looks great! Shouldn't the docs be updated now?

Right now the docs have only the StructuralIdentifiability.jl format (the `@ODEModel`). I will edit the tutorial format. I can copy that tutorial to StructuralIdentifiability.jl docs.

**Comment by iliailmer** [comment]
I added a tutorial on using MTK with StructuralIdentifiability, @pogudingleb

**Comment by pogudingleb** [comment]
@iliailmer  Perfect, thank you!

**Pull request merged**
