### PR TITLE
WIP: use Groebner.jl instead of Singular.jl/GroebnerBasis.jl

### LINKED ISSUE #70: Test StructuralIdentifiability fails : libsingular not defined
Running the MTK tutorial and testing this package fail because of this libsingular not defined error. It has been there since the beginning. Would be good if this issue could finally be resolved so that one can give a real test of this excellent package. 

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.7) pkg> test StructuralIdentifiability
     Testing StructuralIdentifiability
      Status `C:\Users\Denis\AppData\Local\Temp\jl_IbOUUA\Project.toml`
  [c3fe647b] AbstractAlgebra v0.20.1
  [e39c9192] GroebnerBasis v0.3.3
  [c8e1da08] IterTools v1.4.0
  [1914dd2f] MacroTools v0.5.9
  [2edaba10] Nemo v0.25.1
  [27ebfcd6] Primes v0.5.1
  [bcd08a7b] Singular v0.5.8
  [220ca800] StructuralIdentifiability v0.1.0
  [98d24dd4] TestSetExtensions v2.0.0
  [ade2ca70] Dates `@stdlib/Dates`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [8dfed614] Test `@stdlib/Test`
      Status `C:\Users\Denis\AppData\Local\Temp\jl_IbOUUA\Manifest.toml`
  [c3fe647b] AbstractAlgebra v0.20.1
  [b99e7846] BinaryProvider v0.5.10
  [1f15a43c] CxxWrap v0.11.2
  [ab62b9b5] DeepDiffs v1.2.0
  [e39c9192] GroebnerBasis v0.3.3
  [3e1990a7] Hecke v0.10.15
  [c8e1da08] IterTools v1.4.0
  [692b3bcd] JLLWrappers v1.3.0
  [472f376f] LoadFlint v0.5.1
  [1914dd2f] MacroTools v0.5.9
  [2edaba10] Nemo v0.25.1
  [21216c6a] Preferences v1.2.3
  [27ebfcd6] Primes v0.5.1
  [fb686558] RandomExtensions v0.4.3
  [ae029012] Requires v1.2.0
  [bcd08a7b] Singular v0.5.8
  [90137ffa] StaticArrays v1.3.1
  [220ca800] StructuralIdentifiability v0.1.0
  [98d24dd4] TestSetExtensions v2.0.0
  [e21ec000] Antic_jll v0.200.400+0
  [d9960996] Arb_jll v200.1900.1+0
  [fcfa6d1b] Calcium_jll v0.400.0+0
  [e134572f] FLINT_jll v200.700.100+0
  [e8aa6df9] GLPK_jll v5.0.1+0
  [43d676ae] Singular_jll v402.0.104+0
  [f07e07eb] cddlib_jll v0.94.13+0
  [006bdf2e] gb_jll v0.17.0+0
  [1493ae25] lib4ti2_jll v1.6.10+0
  [3eaa8342] libcxxwrap_julia_jll v0.8.8+1
  [ae4fbd8f] libsingular_julia_jll v0.15.7+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [9abbd945] Profile `@stdlib/Profile`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [781609d7] GMP_jll `@stdlib/GMP_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [3a97d323] MPFR_jll `@stdlib/MPFR_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [4536629a] OpenBLAS_jll `@stdlib/OpenBLAS_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850b90] libblastrampoline_jll `@stdlib/libblastrampoline_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
Precompiling project...
  ✗ Singular
  ✗ GroebnerBasis
  ✗ StructuralIdentifiability
  0 dependencies successfully precompiled in 15 seconds (35 already precompiled)
  3 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages
     Testing Running tests...
ERROR: LoadError: UndefVarError: libsingular not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:35
 [2] top-level scope
   @ C:\Users\Denis\.julia\packages\Singular\nGiup\src\Singular.jl:66
 [3] include
   @ .\Base.jl:418 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base .\loading.jl:1318
 [5] top-level scope
   @ none:1
 [6] eval
   @ .\boot.jl:373 [inlined]
 [7] eval(x::Expr)
   @ Base.MainInclude .\client.jl:453
 [8] top-level scope
   @ none:1
in expression starting at C:\Users\Denis\.julia\packages\Singular\nGiup\src\Singular.jl:1
ERROR: LoadError: Failed to precompile Singular [bcd08a7b-43d2-5ff7-b6d4-c458787f915c] to C:\Users\Denis\.julia\compiled\v1.7\Singular\jl_B9D.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1466
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1410
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1120
  [5] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1013
  [6] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:997
  [7] include
    @ .\Base.jl:418 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1318
  [9] top-level scope
    @ none:1
 [10] eval
    @ .\boot.jl:373 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude .\client.jl:453
 [12] top-level scope
    @ none:1
in expression starting at C:\Users\Denis\.julia\packages\GroebnerBasis\89ud7\src\GroebnerBasis.jl:1
ERROR: LoadError: Failed to precompile GroebnerBasis [e39c9192-ea4d-5e15-9584-a488c6d614bd] to C:\Users\Denis\.julia\compiled\v1.7\GroebnerBasis\jl_6AB.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1466
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1410
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1120
  [5] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1013
  [6] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:997
  [7] include
    @ .\Base.jl:418 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1318
  [9] top-level scope
    @ none:1
 [10] eval
    @ .\boot.jl:373 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude .\client.jl:453
 [12] top-level scope
    @ none:1
in expression starting at C:\Users\Denis\.julia\packages\StructuralIdentifiability\wOUIO\src\StructuralIdentifiability.jl:1
ERROR: LoadError: Failed to precompile StructuralIdentifiability [220ca800-aa68-49bb-acd8-6037fa93a544] to C:\Users\Denis\.julia\compiled\v1.7\StructuralIdentifiability\jl_81.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:997
 [7] include(fname::String)
   @ Base.MainInclude .\client.jl:451
 [8] top-level scope
   @ none:6
in expression starting at C:\Users\Denis\.julia\packages\StructuralIdentifiability\wOUIO\test\runtests.jl:1
ERROR: Package StructuralIdentifiability errored during testing

(@v1.7) pkg>

### PR DESCRIPTION
**Pull request by sumiya11**
Hi! It would be nice to escape from a deprecated package, and use windows-compatible groebner bases. For this, I propose integrating `Groebner.jl`, it could fix #70 and #56 . 

Before this replacement could be plausible, there is a minimal todo to cover:
- [x] Produce benchmarks for `Groebner.jl` over rationals
- [x] Implement quotient space operations in `Groebner.jl`: obtaining dimensionality and basis of R/I.  This will be used in `check_primality`
- [ ] ~Implement saturation in `Groebner.jl` to use it in `simplify_field_generators` (?)~
- [x] Currently, `Singular.jl` verifies the resulting basis in rationals, and `Groebner.jl` does not. Add optional result verification in `Groebner.jl`
- [x] Compare the performance of `SI` with `Singular.jl` against the one with `Groebner.jl`

In this PR I'll update on the progress in development of those! Please let me know if I'm missing something 🍰

### CODE REVIEW

**Comment by pogudingleb** [comment]
@sumiya11 , thanks for the summary!
Indeed, I forgot about checking primality, this is some work indeed. Let me think whether there is a workaround.

Saturation is currently done by simply adding a new variable, and we can proceed this way. Of course dedicated algorithm would be cool.

**Comment by sumiya11** [comment]
@pogudingleb do you think we can just check cancellation property for all residuals?

**Comment by pogudingleb** [comment]
> @pogudingleb do you think we can just check cancellation property for all residuals?

Do you mean checking directly whether there are zero divisors? I am a bit sceptical about this. What I thought that one could maybe compute the quotient ring easier thanks to the special form of the polynomials.

**Comment by sumiya11** [comment]
Yep, exactly. Probably checking O(n^2) normal forms over finite field of random characteristic with existing f4 should not be slower than a basis computation itself.
However, I think there could be no need to change `check_primality_zerodim` a lot: I can just implement `kbase` in `Groebner.jl`, which as I understand is not very untrivial having a basis alsready computed

**Comment by pogudingleb** [comment]
Yes, I would expect `kbase` to be relatively straightforward task. By the way, don't you need it for FGLM anyway?

**Comment by sumiya11** [comment]
I do actually!

**Comment by pogudingleb** [comment]
I would go even further an say that I do not really need `kbase` but I use it to compute the [multiplication matrices](https://github.com/SciML/StructuralIdentifiability.jl/blob/master/src/primality_check.jl#L18) modulo the ideal. And I guess you would also compute them if you are doing FGLM, is that correct? (but really would like to have them in char zero...)

**Comment by sumiya11** [comment]
@pogudingleb We use a non-sparse fglm very similar to the one described [here](https://link.springer.com/article/10.1023/A:1022992514981). We don't have multiplication matrices (yet) =(

**Comment by fkrauer** [comment]
is this still WIP? I encounter the same issue with the package not precompiling due to Singular.jl and GroebnerBasis.jl. Thanks!
```
Julia Version 1.7.2
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

**Comment by sumiya11** [comment]
Hi @fkrauer ,  Yes, the work is ongoing ! I still need to get https://github.com/JuliaLang/julia/pull/44566  merged and implement quotient space interface

**Comment by iliailmer** [comment]
@sumiya11 Let me know if you need any help

**Comment by fkrauer** [comment]
> Hi, @fkrauer, this is a known compatibility issue for Windows (e.g. #70). Meanwhile, we have a [Maple web-interface](https://maple.cloud/app/6509768948056064/Structural+Identifiability+Toolbox) for quick and comprehensive identifiability analysis. I hope this helps!

Looks awesome, thanks. I am trying it out now. I hope I didn't break the interface, the model is quite large :/

**Comment by pogudingleb** [comment]
> > Hi, @fkrauer, this is a known compatibility issue for Windows (e.g. #70). Meanwhile, we have a [Maple web-interface](https://maple.cloud/app/6509768948056064/Structural+Identifiability+Toolbox) for quick and comprehensive identifiability analysis. I hope this helps!
> 
> Looks awesome, thanks. I am trying it out now. I hope I didn't break the interface, the model is quite large :/

@fkrauer, if the model does finish, feel free to send it to me. We like challenging models.

**Comment by fkrauer** [comment]
uh sorry there was a typo in the model equations and I reloaded too many times I think  🙈 apologies!

**Comment by sumiya11** [comment]
Yaay, finally `fglm` in Groebner works over rational fields  😄 . So, the quotient space operations should be implemented soon

**Comment by pogudingleb** [comment]
Cool!

**Comment by sumiya11** [comment]
Hi! All needed functions are finally implemented. 

@pogudingleb and I are now testing performance with Groebner.jl vs. Singular  ⏳

**Comment by iliailmer** [comment]
Hi @sumiya11, I tried to run some experiments locally with this code, but I got an error saying 
"ERROR: LoadError: UndefVarError: Singular not defined" 

Will this PR remove Singular.jl from dependencies?

**Comment by pogudingleb** [comment]
@iliailmer 
This PR was more for a discussion and not intended to be run. I am working on removing Singular and switching to Groebner in a separate branch.

**Comment by pogudingleb** [comment]
@fkrauer 
The new version 0.4.0 of the package works on Windows. Please let us know if you encounter any issues with it.

**Pull request closed without merging**
