### PR TITLE
Add Downgrade.yml

### PR DESCRIPTION
**Pull request by sumiya11**
Trying out this new compat CI thing..

See https://julialang.slack.com/archives/CN04R7WKE/p1702296727671319
and https://github.shali-sdc4.acirock.com/marketplace/actions/downgrade-julia-compat-entries

### CODE REVIEW

**Comment by sumiya11** [comment]
As I understand, we should bump Nemo.jl versions to 0.32-0.38 in StructuralIdentifiability.jl ?

https://github.com/SciML/StructuralIdentifiability.jl/actions/runs/7167680162/job/19514247808#step:5:44

At the moment, ParamPunPam.jl restricts Nemo.jl to 0.32-0.37, and StructuralIdentifiability.jl to 0.24-0.38. Hence, the lowest possible bound is 0.32

**Comment by pogudingleb** [comment]
> As I understand, we should bump Nemo.jl versions to 0.32-0.38 in StructuralIdentifiability.jl ?
> 
> https://github.com/SciML/StructuralIdentifiability.jl/actions/runs/7167680162/job/19514247808#step:5:44
> 
> At the moment, ParamPunPam.jl restricts Nemo.jl to 0.32-0.37, and StructuralIdentifiability.jl restricts Nemo.jl to 0.24-0.38. Hence, the lowest possible bound is 0.32

Yes, I agree 0.32 looks like the lowest feasible

**Comment by sumiya11** [comment]
Note for future self: make sure that Groebner.jl v0.6.1 supports Nemo.jl v0.39 (currently it does not https://github.com/sumiya11/Groebner.jl/tree/v0.6.0)

In the light of
https://github.com/SciML/StructuralIdentifiability.jl/pull/260

**Comment by sumiya11** [comment]
@pogudingleb thanks for fixing this! I also have this check in Groebner.jl now

**Pull request merged**
